/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.frames;

import javax.swing.JInternalFrame;

/**
 *
 * @author Sales Macedo
 */
public class telaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public telaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        jMenu1 = new javax.swing.JMenu();
        painelInicial = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuItemCadUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemCadCliente = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemCadProduto = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenu();
        menuItemBuscaCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemBuscaProduto = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        menuItemVendaRealizarVenda = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela inicial");
        setBackground(new java.awt.Color(255, 255, 0));
        setResizable(false);

        painelInicial.setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout painelInicialLayout = new javax.swing.GroupLayout(painelInicial);
        painelInicial.setLayout(painelInicialLayout);
        painelInicialLayout.setHorizontalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        painelInicialLayout.setVerticalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(230, 225, 225));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu3.setText("A.L Bebidas");

        jMenuItem4.setText("Balanço financeiro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Funcionários");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem2.setText("Sobre");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Sair");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        menuCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        menuCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuCadastrar.setText("Cadastrar ");
        menuCadastrar.setMargin(new java.awt.Insets(4, 4, 4, 4));

        menuItemCadUsuario.setText("Usuário");
        menuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadUsuarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadUsuario);
        menuCadastrar.add(jSeparator2);

        menuItemCadCliente.setText("Cliente");
        menuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadCliente);
        menuCadastrar.add(jSeparator3);

        menuItemCadProduto.setText("Produto");
        menuItemCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadProdutoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCadProduto);

        jMenuBar1.add(menuCadastrar);

        menuBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBuscar.setText("Buscar");
        menuBuscar.setMargin(new java.awt.Insets(4, 4, 4, 4));

        menuItemBuscaCliente.setText("Cliente");
        menuItemBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscaClienteActionPerformed(evt);
            }
        });
        menuBuscar.add(menuItemBuscaCliente);
        menuBuscar.add(jSeparator1);

        menuItemBuscaProduto.setText("Produto");
        menuItemBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscaProdutoActionPerformed(evt);
            }
        });
        menuBuscar.add(menuItemBuscaProduto);

        jMenuBar1.add(menuBuscar);

        menuVenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuVenda.setText("Venda");
        menuVenda.setMargin(new java.awt.Insets(4, 4, 4, 4));

        menuItemVendaRealizarVenda.setText("Realizar Venda");
        menuItemVendaRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendaRealizarVendaActionPerformed(evt);
            }
        });
        menuVenda.add(menuItemVendaRealizarVenda);

        jMenuBar1.add(menuVenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(painelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadProdutoActionPerformed
        // TODO add your handling code here:
        JInternalFrame cd = new InternalCadastroProduto();
        painelInicial.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_menuItemCadProdutoActionPerformed

    private void menuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadClienteActionPerformed
        // TODO add your handling code here:
        JInternalFrame cc = new InternalCadastroCliente();
        painelInicial.add(cc);
        cc.setVisible(true);
    }//GEN-LAST:event_menuItemCadClienteActionPerformed

    private void menuItemBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscaClienteActionPerformed
        // TODO add your handling code here:
        JInternalFrame bc = new InternalBuscaCliente();
        painelInicial.add(bc);
        bc.setVisible(true);
    }//GEN-LAST:event_menuItemBuscaClienteActionPerformed

    private void menuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadUsuarioActionPerformed
        // TODO add your handling code here:
       JInternalFrame caduser = new InternalCadastroUsuario();
       painelInicial.add(caduser);
       caduser.setVisible(true);
        
    }//GEN-LAST:event_menuItemCadUsuarioActionPerformed

    private void menuItemBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscaProdutoActionPerformed
        // TODO add your handling code here:
        JInternalFrame bp = new InternalBuscaProduto();
        painelInicial.add(bp);
        bp.setVisible(true);
        
    }//GEN-LAST:event_menuItemBuscaProdutoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JInternalFrame funcionarios = new InternalBuscaUser();
        painelInicial.add(funcionarios);
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuItemVendaRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendaRealizarVendaActionPerformed
        // TODO add your handling code here:
        JInternalFrame venda = new InternalVenda();
        painelInicial.add(venda);
        venda.setLocation(100,10);
        venda.setVisible(true);
    }//GEN-LAST:event_menuItemVendaRealizarVendaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JInternalFrame balanco = new balancoFinanceiro();
        painelInicial.add(balanco);
        balanco.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JMenu menuBuscar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuItemBuscaCliente;
    private javax.swing.JMenuItem menuItemBuscaProduto;
    private javax.swing.JMenuItem menuItemCadCliente;
    private javax.swing.JMenuItem menuItemCadProduto;
    private javax.swing.JMenuItem menuItemCadUsuario;
    private javax.swing.JMenuItem menuItemVendaRealizarVenda;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JPanel painelInicial;
    // End of variables declaration//GEN-END:variables
}
